export const FETCH_CHART_DATA_SUCCESS = 'FETCH_CHART_DATA_SUCCESS';
export const FETCH_CHART_DATA_FAILL = 'FETCH_CHART_DATA_SUCCESS';

export const FETCH_WEEK_CHART_DATA_SUCCESS = 'FETCH_WEEK_CHART_DATA_SUCCESS';
export const FETCH_WEEK_CHART_DATA_FAILL = 'FETCH_WEEK_CHART_DATA_SUCCESS';

export const FETCH_MAX_CHART_DATA_SUCCESS = 'FETCH_MAX_CHART_DATA_SUCCESS';
export const FETCH_MAX_CHART_DATA_FAILL = 'FETCH_MAX_CHART_DATA_SUCCESS';

export const FETCH_QUARTER_CHART_DATA_SUCCESS = 'FETCH_QUARTER_CHART_DATA_SUCCESS';
export const FETCH_QUARTER_CHART_DATA_FAILL = 'FETCH_QUARTER_CHART_DATA_SUCCESS';

export const FETCH_MONTH_CHART_DATA_SUCCESS = 'FETCH_MONTH_CHART_DATA_SUCCESS';
export const FETCH_MONTH_CHART_DATA_FAILL = 'FETCH_MONTH_CHART_DATA_SUCCESS';